dataset:
  common:
    NAME: IndPartNormal
    data_root: E:\data\bylw_indpart\fps_data
    use_normal: True
    num_points: 2048
  train:
    split: trainval
  val:
    split: test
    presample: True

num_classes: 734
shape_classes: 77
num_points: 2048
normal_channel: True
feature_keys: pos,x,heights

datatransforms:
  train: [PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize,PointCloudJitter,ChromaticDropGPU]
  val: [PointsToTensor, PointCloudCenterAndNormalize]
  vote: [PointCloudScaling]
  kwargs:
    jitter_sigma: 0.01
    jitter_clip: 0.05
    scale: [0.8, 1.2]
    gravity_dim: 2
    angle: [0, 0, 1.0]

batch_size: 8
dataloader:
  num_workers: 0

# ---------------------------------------------------------------------------- #
# Evaluation cfgs
# ---------------------------------------------------------------------------- #
num_votes: 10
refine: True 

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #

# lr_scheduler:
lr: 0.001
min_lr: null
optimizer:
  NAME: adamw
  weight_decay: 1.0e-4  # the best 

criterion_args:
  NAME: Poly1FocalLoss

# scheduler
epochs: 150
sched: multistep
decay_epochs: [90, 120]
decay_rate: 0.5
warmup_epochs: 0


sched_on_epoch: True

grad_norm_clip: 1
use_voting: False

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
print_freq: 10
val_freq: 1

# ----------------- Model related

wandb:
  project: DGGAA-IndPart